"""
build_manifest.py — join segments + frames + chapters by timecode; validate vs schema.

Reads:
  - <job_dir>/transcript/segments.jsonl
  - <job_dir>/frames/frames_meta.json
  - <job_dir>/probe_meta.json  (written by run.py after probe stage)

Writes:
  - <job_dir>/manifest.json

The chapters are auto-generated by splitting the duration into equal windows,
with each chapter collecting the segments and frames that fall within its time range.

Usage:
    ~/.venvs/media/bin/python scripts/media/build_manifest.py \
        <job_dir> --slug <slug>
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def load_config() -> dict:
    config_path = Path(__file__).parent / "config" / "defaults.yaml"
    if config_path.exists():
        import yaml  # noqa: PLC0415

        with config_path.open() as fh:
            return yaml.safe_load(fh) or {}
    return {}


def load_segments(job_dir: Path) -> list[dict]:
    path = job_dir / "transcript" / "segments.jsonl"
    if not path.exists():
        return []
    segs = []
    with path.open(encoding="utf-8") as fh:
        for line in fh:
            line = line.strip()
            if line:
                segs.append(json.loads(line))
    return segs


def load_frames(job_dir: Path) -> list[dict]:
    path = job_dir / "frames" / "frames_meta.json"
    if not path.exists():
        return []
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def load_probe_meta(job_dir: Path) -> dict:
    path = job_dir / "probe_meta.json"
    if not path.exists():
        return {}
    with path.open(encoding="utf-8") as fh:
        return json.load(fh)


def auto_chapters(
    segments: list[dict],
    frames: list[dict],
    duration: float,
    target_count: int,
    min_duration: float,
) -> list[dict]:
    """
    Auto-generate chapters by splitting duration into equal windows.
    Each chapter collects segments and frames in its time range.
    """
    if duration <= 0:
        return []

    # Clamp target count so each chapter meets min_duration
    max_chapters = max(1, int(duration / min_duration))
    count = min(target_count, max_chapters)
    chapter_dur = duration / count

    chapters = []
    for i in range(count):
        t_start = round(i * chapter_dur, 3)
        t_end = round((i + 1) * chapter_dur, 3)
        if i == count - 1:
            t_end = round(duration, 3)

        ch_id = f"c{i + 1:02d}"

        seg_ids = [
            s["id"]
            for s in segments
            if s.get("t_start", 0) >= t_start and s.get("t_start", 0) < t_end
        ]

        frame_ids = [f["id"] for f in frames if f.get("t", 0) >= t_start and f.get("t", 0) < t_end]

        # Collect text for summary
        chapter_texts = [s["text"] for s in segments if s["id"] in seg_ids]
        summary_text = " ".join(chapter_texts)
        # Simple summary: first sentence or first 120 chars
        summary = _extract_summary(summary_text)

        # Simple keyword extraction: most common words > 4 chars
        keywords = _extract_keywords(summary_text)

        chapters.append(
            {
                "id": ch_id,
                "title": f"Section {i + 1}",
                "t_start": t_start,
                "t_end": t_end,
                "summary": summary,
                "keywords": keywords,
                "segment_ids": seg_ids,
                "frame_ids": frame_ids,
            }
        )

    return chapters


def _extract_summary(text: str, max_chars: int = 200) -> str:
    text = text.strip()
    if not text:
        return ""
    # Take up to first period or max_chars
    period_idx = text.find(".")
    if 0 < period_idx <= max_chars:
        return text[: period_idx + 1]
    return text[:max_chars] + ("…" if len(text) > max_chars else "")


def _extract_keywords(text: str, max_kw: int = 5) -> list[str]:
    import re  # noqa: PLC0415

    words = re.findall(r"[a-zA-Z]{4,}", text.lower())
    stop = {
        "that",
        "this",
        "with",
        "have",
        "from",
        "they",
        "will",
        "been",
        "your",
        "what",
        "when",
        "then",
        "just",
        "more",
        "also",
        "some",
        "into",
        "here",
        "about",
        "going",
        "going",
        "click",
        "button",
        "okay",
        "like",
        "need",
        "want",
        "over",
        "next",
        "look",
    }
    freq: dict[str, int] = {}
    for w in words:
        if w not in stop:
            freq[w] = freq.get(w, 0) + 1
    top = sorted(freq, key=lambda w: -freq[w])[:max_kw]
    return top


def validate_manifest(manifest: dict, schema_path: Path) -> None:
    import jsonschema  # noqa: PLC0415

    with schema_path.open() as fh:
        schema = json.load(fh)
    try:
        jsonschema.validate(instance=manifest, schema=schema)
    except jsonschema.ValidationError as exc:
        print(f"build_manifest: ERROR — manifest validation failed: {exc.message}", file=sys.stderr)
        sys.exit(1)


def verify_frame_ids_on_disk(frames: list[dict], job_dir: Path) -> list[str]:
    """Return list of frame IDs whose files are missing on disk."""
    missing = []
    for f in frames:
        fpath = job_dir / f["path"]
        if not fpath.exists():
            missing.append(f["id"])
    return missing


def build_manifest(job_dir: Path, slug: str) -> None:
    cfg = load_config()
    chapters_cfg = cfg.get("chapters", {})
    target_count = int(chapters_cfg.get("target_count", 8))
    min_duration = float(chapters_cfg.get("min_duration_sec", 20))

    segments = load_segments(job_dir)
    frames = load_frames(job_dir)
    probe_meta = load_probe_meta(job_dir)

    if not segments:
        print("build_manifest: WARNING — no segments found", file=sys.stderr)

    duration = probe_meta.get("duration_sec", 0.0)
    if not duration and segments:
        duration = max(s.get("t_end", 0) for s in segments)

    source_file = probe_meta.get("source_file", "source/original.mp4")
    source_type = probe_meta.get("source_type", "video")
    language = "en"  # from transcription info if available
    raw_json = job_dir / "transcript" / "raw.json"
    if raw_json.exists():
        with raw_json.open() as fh:
            raw = json.load(fh)
            language = raw.get("info", {}).get("language", "en")

    chapters = auto_chapters(segments, frames, duration, target_count, min_duration)

    # Build manifest segments (add frame_ids cross-reference)
    manifest_segments = []
    for seg in segments:
        t_start = seg.get("t_start", 0)
        t_end = seg.get("t_end", t_start)
        frame_ids = [f["id"] for f in frames if f.get("t", 0) >= t_start and f.get("t", 0) <= t_end]
        manifest_segments.append(
            {
                "id": seg["id"],
                "t_start": seg["t_start"],
                "t_end": seg["t_end"],
                "text": seg["text"],
                "no_speech_prob": seg.get("no_speech_prob", 0.0),
                "frame_ids": frame_ids,
            }
        )

    manifest = {
        "job": {
            "slug": slug,
            "source_file": source_file,
            "source_type": source_type,
            "duration_sec": round(duration, 3),
            "language": language,
            "media_sha256": probe_meta.get("media_sha256", ""),
            "pipeline_version": cfg.get("pipeline_version", "1.0"),
            "created_utc": datetime.now(timezone.utc).isoformat(),
        },
        "stages": {
            "probe": "done",
            "audio": "done",
            "transcribe": "done",
            "frames": "done",
            "manifest": "done",
            "index": "pending",
            "proofed": "pending",
        },
        "segments": manifest_segments,
        "frames": frames,
        "chapters": chapters,
    }

    # Validate against schema
    schema_path = Path(__file__).parent / "schema" / "manifest.schema.json"
    if schema_path.exists():
        validate_manifest(manifest, schema_path)
        print("build_manifest: schema validation passed")

    # Verify all frame IDs are on disk
    missing_frames = verify_frame_ids_on_disk(frames, job_dir)
    if missing_frames:
        print(
            f"build_manifest: WARNING — {len(missing_frames)} frame file(s) missing on disk: "
            f"{missing_frames[:5]}",
            file=sys.stderr,
        )

    out_path = job_dir / "manifest.json"
    with out_path.open("w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)
    print(f"build_manifest: wrote {out_path}")
    print(f"  segments : {len(manifest_segments)}")
    print(f"  frames   : {len(frames)}")
    print(f"  chapters : {len(chapters)}")


def main() -> None:
    parser = argparse.ArgumentParser(description="Build manifest.json from pipeline artifacts")
    parser.add_argument("job_dir", type=Path, help="Job directory root")
    parser.add_argument("--slug", required=True, help="Job slug")
    args = parser.parse_args()

    if not args.job_dir.exists():
        print(f"build_manifest: ERROR — job_dir not found: {args.job_dir}", file=sys.stderr)
        sys.exit(1)

    build_manifest(args.job_dir, args.slug)


if __name__ == "__main__":
    main()
