"""
build_index.py — build index.md (the read-first chapter map) from manifest.json.

Output format:
  - YAML front matter: slug, duration_sec, chapter_count, created_utc
  - One section per chapter: title, time range, summary, keywords, frame IDs.

Validates full duration coverage (no gaps, all time accounted for).

Usage:
    ~/.venvs/media/bin/python scripts/media/build_index.py <job_dir>
"""

import argparse
import json
import sys
from datetime import datetime, timezone
from pathlib import Path


def seconds_to_hms(secs: float) -> str:
    s = int(secs)
    h = s // 3600
    m = (s % 3600) // 60
    sec = s % 60
    if h > 0:
        return f"{h}:{m:02d}:{sec:02d}"
    return f"{m}:{sec:02d}"


def validate_coverage(chapters: list[dict], duration: float, tolerance: float = 2.0) -> list[str]:
    """Return list of coverage problems (gaps / overlaps)."""
    problems = []
    if not chapters:
        problems.append("no chapters defined")
        return problems

    sorted_ch = sorted(chapters, key=lambda c: c["t_start"])

    # Check first chapter starts near 0
    if sorted_ch[0]["t_start"] > tolerance:
        problems.append(f"gap before first chapter: 0 → {sorted_ch[0]['t_start']:.1f}s")

    # Check last chapter ends near duration
    if abs(sorted_ch[-1]["t_end"] - duration) > tolerance:
        problems.append(
            f"last chapter ends at {sorted_ch[-1]['t_end']:.1f}s but duration is {duration:.1f}s"
        )

    # Check gaps between chapters
    for i in range(1, len(sorted_ch)):
        prev_end = sorted_ch[i - 1]["t_end"]
        curr_start = sorted_ch[i]["t_start"]
        if abs(curr_start - prev_end) > tolerance:
            problems.append(
                f"gap between chapters {i} and {i + 1}: {prev_end:.1f}s → {curr_start:.1f}s"
            )

    return problems


def build_index(job_dir: Path) -> None:
    manifest_path = job_dir / "manifest.json"
    if not manifest_path.exists():
        print(f"build_index: ERROR — manifest.json not found: {manifest_path}", file=sys.stderr)
        sys.exit(1)

    with manifest_path.open(encoding="utf-8") as fh:
        manifest = json.load(fh)

    job = manifest["job"]
    chapters = manifest.get("chapters", [])
    duration = job.get("duration_sec", 0.0)

    # Validate coverage
    problems = validate_coverage(chapters, duration)
    if problems:
        for p in problems:
            print(f"build_index: WARNING — {p}", file=sys.stderr)

    now_utc = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")

    lines = []

    # YAML front matter
    lines.append("---")
    lines.append(f"slug: {job['slug']}")
    lines.append(f"duration_sec: {duration}")
    lines.append(f'duration_hms: "{seconds_to_hms(duration)}"')
    lines.append(f"chapter_count: {len(chapters)}")
    lines.append(f"language: {job.get('language', 'en')}")
    lines.append(f"source_type: {job.get('source_type', 'video')}")
    lines.append(f"created_utc: {now_utc}")
    lines.append(f"pipeline_version: {job.get('pipeline_version', '1.0')}")
    lines.append("---")
    lines.append("")
    lines.append(f"# {job['slug']} — index")
    lines.append("")
    lines.append(
        "> **Read this file first.** "
        "It maps every chapter to its transcript segments and frames. "
        "Load only the sections relevant to your task."
    )
    lines.append("")
    lines.append(f"**Duration:** {seconds_to_hms(duration)} ({duration:.0f}s)  ")
    lines.append(f"**Chapters:** {len(chapters)}  ")
    lines.append(f"**Language:** {job.get('language', 'en')}  ")
    lines.append("")
    lines.append("---")
    lines.append("")

    for ch in sorted(chapters, key=lambda c: c["t_start"]):
        t_range = f"{seconds_to_hms(ch['t_start'])}–{seconds_to_hms(ch['t_end'])}"
        lines.append(f"## {ch['id'].upper()}: {ch['title']}")
        lines.append("")
        lines.append(f"**Time:** {t_range}  ")
        lines.append(f"**Summary:** {ch['summary']}  ")

        if ch.get("keywords"):
            lines.append(f"**Keywords:** {', '.join(ch['keywords'])}  ")

        if ch.get("frame_ids"):
            lines.append(f"**Frames:** {', '.join(ch['frame_ids'])}  ")

        if ch.get("segment_ids"):
            lines.append(
                f"**Segments:** {', '.join(ch['segment_ids'][:5])}"
                + (" …" if len(ch["segment_ids"]) > 5 else "")
                + "  "
            )

        lines.append("")

    # Append trailing note
    lines.append("---")
    lines.append("")
    lines.append(
        "_Generated by media pipeline. "
        "For full transcript, load `transcript/segments.jsonl`. "
        "For machine join, load `manifest.json`._"
    )
    lines.append("")

    index_path = job_dir / "index.md"
    with index_path.open("w", encoding="utf-8") as fh:
        fh.write("\n".join(lines))
    print(f"build_index: wrote {index_path}")
    print(f"  chapters   : {len(chapters)}")
    print(f"  duration   : {seconds_to_hms(duration)}")
    if problems:
        print(f"  coverage   : {len(problems)} warning(s) — see stderr")
    else:
        print("  coverage   : full (no gaps)")

    # Update manifest stages marker
    with manifest_path.open(encoding="utf-8") as fh:
        manifest = json.load(fh)
    manifest["stages"]["index"] = "done"
    with manifest_path.open("w", encoding="utf-8") as fh:
        json.dump(manifest, fh, indent=2, ensure_ascii=False)


def main() -> None:
    parser = argparse.ArgumentParser(description="Build index.md from manifest.json")
    parser.add_argument("job_dir", type=Path, help="Job directory root")
    args = parser.parse_args()

    build_index(args.job_dir)


if __name__ == "__main__":
    main()
